import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Work_Sans } from "next/font/google";
import "./globals.css";
import ClientSessionProvider from "@/app/components/ClientSessionProvider"; // Імпортуємо ClientSessionProvider

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

const workSans = Work_Sans({
    variable: "--font-work-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
        <head>
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link
                rel="preconnect"
                href="https://fonts.gstatic.com"
                crossOrigin="anonymous"
            />
            <link
                href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Source+Serif+4:ital,opsz,wght@0,8..60,200..900;1,8..60,200..900&family=Work+Sans:ital,wght@0,100..900;1,100..900&display=swap"
                rel="stylesheet"
            />
        </head>
        {/* Використовуємо ClientSessionProvider */}
        <ClientSessionProvider>
            <body
                className={`
                    ${geistSans.variable}
                    ${geistMono.variable}
                    ${inter.variable}
                    ${workSans.variable}
                    antialiased
                `}
            >
            {children}
            </body>
        </ClientSessionProvider>
        </html>
    );
}
